version: "3.7"

services:
  mongo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../backend:/myfolder/backend
    ports:
      - 3000:3000

  mongo-database:
    image: mongo:5
    ports:
      - 27017:27017
